image: debian:bookworm
pages:
  script:
    - sed -i 's/main/main non-free/' /etc/apt/sources.list.d/*
    - apt-get update && apt-get -y install xml2rfc ruby-kramdown-rfc2629 make git python3
    - make draft-amsuess-core-coap-over-gatt.html
    - mkdir -p public
    - cp draft-amsuess-core-coap-over-gatt.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
